name: assignments_test
on: push
jobs:
  run_assignments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Clone cse1110/assignments
        uses: actions/checkout@v3
        with:
          repository: 'cse1110/assignments'
          path: 'assignments'

      - name: Compile Andy
        run: |
          mvn clean compile dependency:copy-dependencies

      - name: Execute python script
        run: |
          python ./.github/scripts/assignments_test.py
